version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y curl unzip

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 041124310096.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_URI=041124310096.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app
      - export IMAGE_TAG=latest

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Deploying to EKS..."
      - aws eks update-kubeconfig --region us-east-1 --name brain-tasks-cluster
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

