apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
data:
  cwagentconfig.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/nginx/access.log",
                "log_group_name": "/brain-tasks/nginx-access",
                "log_stream_name": "{hostname}/access.log",
                "timestamp_format": "%d/%b/%Y:%H:%M:%S %z"
              },
              {
                "file_path": "/var/log/nginx/error.log",
                "log_group_name": "/brain-tasks/nginx-error",
                "log_stream_name": "{hostname}/error.log"
              }
            ]
          }
        }
      }
    }

