apiVersion: v1
kind: Pod
metadata:
  name: image-pull-test
spec:
  containers:
  - name: test
    image: 041124310096.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:v1
    command: [ "sleep", "3600" ]
  restartPolicy: Never

